source 'https://rubygems.org'

ruby '~> 4.0'

gem 'keenetic', github: 'antonzaytsev/keenetic-ruby'

gem 'rackup'
gem 'roda'
gem 'puma'
gem 'rack-cors'
gem 'logger'
gem 'pry'

group :development, :test do
  gem 'rspec'
  gem 'webmock'
  gem 'rack-test'
  gem 'rerun'
  gem 'listen'
end
